namespace EdgeEx.WinUI3.Enums
{
    public enum ResourceKey
    {
        AppTitle,
        WindowBackdrop,
        ThemeSettings,
        WindowBackdropDescription,
        About,
        Shomnipotence,
        AuthorTeam,
        Dependencies,
        Open,
        Log,
        OtherSelection,
        UICode,
        MicaAppsTitle,
        MicaAppsDes,
        MicaCraftDes,
        BugRequest,
        RefreshBackdrop,
        Reset,
        Acrylic,
        Mica,
        TintColor,
        TintOpacity,
        FallbackColor,
        MicaKind,
    }
}