// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Winui3Cef
{
    [default_interface]
    runtimeclass CefView : Microsoft.UI.Xaml.Controls.UserControl
    {
        CefView();

        /*Webview2 methods*/
        Boolean CanGoBack{ get; };
        void GoBack();

        Boolean CanGoForward{ get; };
        void GoForward();

        Windows.UI.Color DefaultBackgroundColor{ get; };
        Windows.Foundation.Uri Source{ get; set; };
        void NavigateToString(String htmlContent);
        void Close();
        Windows.Foundation.IAsyncOperation<String> ExecuteScriptAsync(String javascriptCode);

        //void CanLoad();
        //
        //event Windows.Foundation.EventHandler<String> WebMessageReceived;
        //void ExecuteScript(String script);
    }
}
